<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="runtimes\linux-x64\"/>
    </ItemGroup>

    <PropertyGroup>
        <PackageId>FrLv2</PackageId>
        <Version>0.0.4</Version>
        <Authors>Frank Krick</Authors>
        <Description>dotnet LV2 Library - For plugin info parsing</Description>
        <PackageTags>linux;lv2;native</PackageTags>
    </PropertyGroup>

    <PropertyGroup>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <RepositoryUrl>https://git.sr.ht/~frank6/wp-lv2</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
    </PropertyGroup>

    <ItemGroup>
        <None Include="runtimes/linux-x64/libfrlv2.so.0.0.3" Pack="true" PackagePath="runtimes/linux-x64/native/"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" CopyToPublishDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="all"/>
    </ItemGroup>

</Project>
