<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>FrWireplumber</PackageId>
        <Version>0.9.3</Version>
        <Authors>Frank Krick</Authors>
        <Description>dotnet Wireplumber Library - For session monitoring and control</Description>
        <PackageTags>linux;wireplumber;pipewire;native</PackageTags>
    </PropertyGroup>

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    
    <PropertyGroup>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <RepositoryUrl>https://git.sr.ht/~frank6/wp-dotnet</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
    </PropertyGroup>

    <ItemGroup>
        <None Include="runtimes/linux-x64/libfrwireplumber.so.0.9.1" Pack="true" PackagePath="runtimes/linux-x64/native/"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" CopyToPublishDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="all"/>
    </ItemGroup>
    
    <!-- Allow test assembly to call internal methods -->
    <ItemGroup>
        <InternalsVisibleTo Include="Fr.Wireplumber.Tests" />
    </ItemGroup>
</Project>
