<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.0.1" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.0.0" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.0.1" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.1" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.1" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="11.4.12" />
        <PackageReference Include="Serilog" Version="4.3.1" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="System.Reactive" Version="6.1.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\SaveFilterGraphDialogViews\SaveFilterGraphDialogView.axaml.cs">
          <DependentUpon>SaveFilterGraphDialogView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Controls\MixerControls\ChannelDetailsSection.axaml.cs">
          <DependentUpon>ChannelDetailsSection.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MixerViewsV2\AddFilterChainView.axaml.cs">
          <DependentUpon>AddFilterChainView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Controls\MixerControls\GroupChannelStrip.axaml.cs">
          <DependentUpon>GroupChannelStrip.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Controls\MixerControls\MasterChannelStrip.axaml.cs">
          <DependentUpon>MasterChannelStrip.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\FilterGraph\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SonicEddy.Contracts\SonicEddy.Contracts.csproj" />
      <ProjectReference Include="..\Fr.Pw.Midi\Fr.Pw.Midi.csproj" />
      <ProjectReference Include="..\Fr.Wireplumber\Fr.Wireplumber.csproj" />
      <ProjectReference Include="..\Fr.Pw.Monitoring\Fr.Pw.Monitoring.csproj" />
      <ProjectReference Include="..\Fr.Lv2\Fr.Lv2.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\Fr.Pw.Midi\runtimes\linux-x64\libfrmidimapper.so.0.0.4" CopyToOutputDirectory="PreserveNewest">
            <Link>runtimes\linux-x64\native\libfrmidimapper.so.0.0.4</Link>
        </None>
        <None Include="..\Fr.Wireplumber\runtimes\linux-x64\libfrwireplumber.so.0.9.1" CopyToOutputDirectory="PreserveNewest">
            <Link>runtimes\linux-x64\native\libfrwireplumber.so.0.9.1</Link>
        </None>
        <None Include="..\Fr.Pw.Monitoring\runtimes\linux-x64\libfrmonitoring.so.0.0.4" CopyToOutputDirectory="PreserveNewest">
            <Link>runtimes\linux-x64\native\libfrmonitoring.so.0.0.4</Link>
        </None>
        <None Include="..\Fr.Lv2\runtimes\linux-x64\libfrlv2.so.0.0.3" CopyToOutputDirectory="PreserveNewest">
            <Link>runtimes\linux-x64\native\libfrlv2.so.0.0.3</Link>
        </None>
    </ItemGroup> 
</Project>
