<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>disable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.0" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.0" />
        <PackageReference Include="Avalonia.Controls.ItemsRepeater" Version="12.0.0" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
        <PackageReference Include="Avalonia.Wayland" Version="12.1.0" />
        <PackageReference Include="NWayland" Version="0.11.0" />
        <PackageReference Include="ReactiveUI.Avalonia" Version="12.0.3" />
        <PackageReference Include="Serilog" Version="4.4.0" />
        <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageReference Include="System.Reactive" Version="7.0.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\SaveFilterGraphDialogViews\SaveFilterGraphDialogView.axaml.cs">
          <DependentUpon>SaveFilterGraphDialogView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Controls\MixerControls\ChannelDetailsSection.axaml.cs">
          <DependentUpon>ChannelDetailsSection.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MixerViewsV2\AddFilterChainView.axaml.cs">
          <DependentUpon>AddFilterChainView.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Controls\MixerControls\GroupChannelStrip.axaml.cs">
          <DependentUpon>GroupChannelStrip.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Controls\MixerControls\MasterChannelStrip.axaml.cs">
          <DependentUpon>MasterChannelStrip.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Models\FilterGraph\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SonicEddy.Contracts\SonicEddy.Contracts.csproj" />
      <ProjectReference Include="..\Fr.Sonic\Fr.Sonic.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\fr-sonic\build\src\libfrsonic.so.0.5.0" CopyToOutputDirectory="PreserveNewest">
            <Link>runtimes\linux-x64\native\libfrsonic.so.0.5.0</Link>
        </None>
    </ItemGroup>
</Project>
