<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>FrPwMonitoring</PackageId>
        <Version>0.0.4</Version>
        <Authors>Frank Krick</Authors>
        <Description>dotnet pipewire library for monitoring</Description>
        <PackageTags>linux;pipewire;native</PackageTags>
    </PropertyGroup>

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <PropertyGroup>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
    </PropertyGroup>

    <PropertyGroup>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <PropertyGroup>
        <RepositoryUrl>https://git.sr.ht/~frank6/pw-monitoring-dotnet</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
    </PropertyGroup>

    <ItemGroup>
        <None Include="runtimes/linux-x64/libfrmonitoring.so.0.0.4" Pack="true" PackagePath="runtimes/linux-x64/native/"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" CopyToPublishDirectory="PreserveNewest"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="all"/>
    </ItemGroup>
</Project>
